# 异常
crtl+alt+T，将选择代码进行try-catch，使其在出现异常后仍能继续执行
## 异常类型
>编译异常必须处理，运行不用
```
Exception
├─ RuntimeException
│  ├─ NullPointerException
│  ├─ IndexOutOfBoundsException
│  ├─ SecurityException
│  └─ IllegalArgumentException
│     └─ NumberFormatException
├─ IOException
│  ├─ UnsupportedCharsetException
│  ├─ FileNotFoundException
│  └─ SocketException
├─ ParseException
├─ GeneralSecurityException
├─ SQLException
└─ TimeoutException
```
运行异常:空指针异常NullPointerException，数学算数异常arithmeticException，数组下标越界异常ArryIndexOutofBoundsException,类型转换异常ClassCastExceotipms,数字格式不正确异常NumberFormatException

编译异常:查询异常SQLException，操作文件异常IOException，文件不存在异常FileNotFoundException，类不存在异常ClassNotFoundException

## 异常处理机制
### try-catch-finally
```java
//finally可以没有
try{
可能会出现异常的代码
}catch（Exception e）{
异常发生时，将异常封装成对象e后传入
没有发生异常，catch里的不执行
}finally{
不管异常发没发生，都会执行。
通常放释放资源的代码
}
//如果finally有return，在catch里的return不返回但会执行；要返回或者抛出异常，先得执行finally里的内容
```
### thows
默认处理机制thows，不断向父类抛，抛到最后jvm报错

## 自定义异常thow
```java
//构造方法原样照抄RuntimeException。这样，抛出异常的时候，就可以选择合适的构造方法
public class BaseException extends RuntimeException {
    public BaseException() {
        super();
    }

    public BaseException(String message, Throwable cause) {
        super(message, cause);
    }

    public BaseException(String message) {
        super(message);
    }

    public BaseException(Throwable cause) {
        super(cause);
    }
}
public class IllegalArgumentException extends BaseException {
    public IllegalArgumentException() {
        super();
    }

    public IllegalArgumentException(String message, Throwable cause) {
        super(message, cause);
    }

    public IllegalArgumentException(String message) {
        super(message);
    }

    public IllegalArgumentException(Throwable cause) {
        super(cause);
    }
}

//自定义异常抛出
if(x<1>){
throw new IllegalArgumentException();
}

```
